<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>grammar</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>Hammer</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*([\w]+)\s*(=)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.rule.hammer</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.rule.hammer</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)\s*</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.rule.hammer</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.rule.hammer</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule_body</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>.+</string>
			<key>name</key>
			<string>invalid.illegal.invalid-rule.hammer</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>alternation</key>
		<dict>
			<key>match</key>
			<string>\|</string>
			<key>name</key>
			<string>keyword.operator.logical.alternation.hammer</string>
		</dict>
		<key>character_set</key>
		<dict>
			<key>begin</key>
			<string>(\[)(\^)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.character-set.begin.hammer</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.logical.character-set.hammer</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.character-set.end.hammer</string>
				</dict>
			</dict>
			<key>name</key>
			<string>constant.other.character-set.hammer</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(w|s|d|n|r|t)</string>
					<key>name</key>
					<string>constant.character.character-set.hammer</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[^\]]</string>
					<key>name</key>
					<string>constant.character.character-set.backslash.hammer</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\]</string>
					<key>name</key>
					<string>constant.character.character-set.escape.hammer</string>
				</dict>
			</array>
		</dict>
		<key>double_quoted_string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.quoted.double.begin.hammer</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.quoted.double.end.hammer</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.hammer</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.hammer</string>
				</dict>
			</array>
		</dict>
		<key>group</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.group.begin.hammer</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.group.end.hammer</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.group.hammer</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule_body</string>
				</dict>
			</array>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.hammer</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.hammer</string>
		</dict>
		<key>missing_terminator</key>
		<dict>
			<key>begin</key>
			<string>\w+\s*=</string>
			<key>end</key>
			<string>(?=;)</string>
			<key>name</key>
			<string>invalid.illegal.rule-definition.hammer</string>
		</dict>
		<key>named_subrule</key>
		<dict>
			<key>begin</key>
			<string>(\()\s*(\w+)\s*(=)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.group.named.begin.hammer</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.hammer</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.group.named.hammer</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.group.named.end.hammer</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.group.named.hammer</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule_body</string>
				</dict>
			</array>
		</dict>
		<key>reference</key>
		<dict>
			<key>match</key>
			<string>\w+</string>
			<key>name</key>
			<string>support.function.rule.hammer</string>
		</dict>
		<key>repetition</key>
		<dict>
			<key>match</key>
			<string>\?|\*|\+|\{\d?,?\d?\}</string>
			<key>name</key>
			<string>keyword.operator.logical.repetition.hammer</string>
		</dict>
		<key>rule_body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#double_quoted_string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single_quoted_string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#character_set</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#named_subrule</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#group</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#missing_terminator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#alternation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#repetition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
			</array>
		</dict>
		<key>single_quoted_string</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.quoted.single.begin.hammer</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.quoted.single.end.hammer</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.hammer</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.hammer</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.hammer</string>
	<key>uuid</key>
	<string>40DF9A3E-23D1-4C58-B99A-2AEB6C6BC050</string>
</dict>
</plist>
